### ISSUE TITLE
GulpUglifyError: unable to minify JavaScript

### ISSUE THREAD

**Issue by alirazaalvi** [ngryman/tree-crawl#13]
I am getting 'GulpUglifyError: unable to minify JavaScript' when gulp is trying to minify tree-crawl. It may be happening because of the files in dist folder are in es6 and gulp uglify accepts es5 code.

**Comment by ngryman** [comment]
Hey!

I suppose you target a browser environment. I provide a different bundle for browsers that contains `es5` code (`dist/tree-crawl.browser.js`). It is referenced by the `browser` property in `package.json` that any modern bundler should be able to use.

What bundler are you using?

**Comment by alirazaalvi** [comment]
I am using gulp with browserify. and it works fine until i do the uglification with gulp uglify.

**Comment by ngryman** [comment]
Ok, so I confirm that `browserify` uses `tree-crawl.browser.js` which contains `es5` code.

But it seems that `lib/context.js` is not included in `tree-crawl.browser.js` as it should be. Instead it's resolved by your `browserify` at bundling time and it does contains `es6` code. Your error comes from this I guess.

I'll make sure I fix the build script asap.

**Comment by ngryman** [comment]
@alirazaalvi I've pushed a potential fix, could you try with it? Just put `ngryman/tree-crawl` in your `package.json` and install again. Thanks!

**Comment by alirazaalvi** [comment]
Is it published to npm? I did npm install --save tree-crawl and it downloaded the version 0.5.0 from npm repository which doesn't have the new changes.

**Comment by ngryman** [comment]
The build process is defined in the `meta-dev` package that I updated to address this issue.
I didn't released a new version on `npm` yet. I want to validate with you that the new build works before doing so. `npm install tree-crawl` will do nothing.

To grab the latest changes you have to mention `npm|yarn` to fetch directly from `git` hence the `ngryman/tree-crawl` syntax which is a shorthand for defining a `github` repository.
You better alter your project's `package.json` and set `tree-crawl` as a dependency like this:

```json
"dependencies": {
  "tree-crawl": "ngryman/tree-crawl"
}
```

Then you can run `npm|yarn install` and it will grab the latest changes

**Comment by alirazaalvi** [comment]
I tried it and now i am getting this error "SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'".

**Comment by ngryman** [comment]
@alirazaalvi Ok, may I have access to your repo or more details about your `package.json` and `gulpfile.js` so I can understand exactly what's happening? Thanks!

**Comment by alirazaalvi** [comment]
I created a minimal repo https://github.com/alirazaalvi/treecrawltest. Just do the npm install or yarn and run the gulp. You will get the error.

**Comment by ngryman** [comment]
Thanks! I figured it out.

I only build dist bundles when publishing to `npm` (`prepublish` hook). As I didn't published it, you didn't have those bundles and `browserify` fell back to the `main` field in the `package.json` that points to `es6` code. I published `0.6.1` with the fix, tested with you code, and the error disappears. But, `uglify` was still crashing...

So I analyzed your output bundle (`react-vendors.js`), and `es6` code was still present in there... After looking at your `gulpfile.js`, I realized that you were using `resolve` along with `browserify.require`. The problem was that, `resolve` was not using the `browser` field in your `package.json` but was resolving to `dist/tree-crawl.node.js` instead of `dist/tree-crawl.browser.js`. I didn't figured out how to configure it to do so, but I guess it's possible.
It turns out that if you are only referring to 3rd party modules and don't need to alter their required name, the `expose` option to `browserify.require` is not necessary, and you can simply do `vendors.require(item);` and let `browserify` resolve modules internally.

I tested with this and it finally worked!

**Comment by ngryman** [comment]
Associated PR to your example project: https://github.com/alirazaalvi/treecrawltest/pull/1.

**Comment by alirazaalvi** [comment]
Worked perfectly. Thank you very much for helping me out.

**Comment by ngryman** [comment]
You're welcome!
