### ISSUE TITLE
A way to stop and resume the iteration

### ISSUE THREAD

**Issue by mcalus3** [ngryman/tree-crawl#51]
I have a case in which I would like to arbitrarily suspend and later resume the iteration. I have a large tree structure, traversing through which would take a very long time and I would like to do it in 16 ms time slices to not block the UI and give live preview of the effect of traversal.

You can see my project here: https://github.com/mcalus3/open-fraksl (tree-crawl is used for rendering fractal elements, number of which multiplies with every depth level, that's why there is so much of them).

It would be helpful if you guide me, show where to add such a function and I would like to add it myself, as a pull request :)

**Comment by mcalus3** [comment]
I wonder if I could convert crawl function (and other, functions called inside) to async and then in *iteratee* function just write:
`
await new Promise(resolve => requestAnimationFrame(resolve))
`

That should suspend crawling, execute all code waiting in the callback queue and then resume crawling. Am I right?

**Comment by ngryman** [comment]
Hey @mcalus3, sorry for the late answer.

In order to support async traversal, I would need to patch `tree-crawl` to add support for iteratees that return a promise. It would be a pretty trivial change but I would need to double check how it impacts performance.

---

That being said I wonder if you couldn't come up with a good solution using the current sync version. I didn't go into the details of your implementation but I suspect you could do something like this:

```ts
const renderFractal = (root) => {
  let currentNode = root

  const renderPass = () => {
    const startTime = performance.now()

    crawl(currentNode, (node, context) => {
      render(node)
    
      if (performance.now() - startTime >= 16) {
        context.break()
        currentNode = node
      }
    })

    requestAnimationFrame(renderPass)
  }

  renderPass()
}
```

**Comment by mcalus3** [comment]
From what I understand, your proposed function would resume (after Request Animation Frame call) with the node it suspended on being a new root node. For example, if it suspended on node 5 on attached structure:

https://www.cdn.geeksforgeeks.org/wp-content/uploads/binary-tree-to-DLL.png

it would set it as a new root node and render only nodes 10 and 11 (omitting 6,7,13,14).
What I need is being able to call "crawl" function not only with giving the node 5 as starting node, I would have also to capture the queue at the moment of break and resume next call with it.

So, I would need new option to the "crawl" function arguments and a new function on crawl context to use them like this:

```js
const renderFractal = root => {
  let currentNode = root;
  let currentQueue = []; // 🔴

  const renderPass = () => {
    const startTime = performance.now();

    crawl(
      currentNode,
      (node, context) => {
        render(node);

        if (performance.now() - startTime >= 16) {
          context.break();
          currentNode = node;
          currentQueue = context.getQueue(); // 🔴
        }
      },
      { currentQueue: currentQueue } // 🔴
    );

    requestAnimationFrame(renderPass);
  };

  renderPass();
};
```

If you like this idea, I could implement it and open a PR :)

**Comment by mcalus3** [comment]
I've researched the topic and experimentally added a possibility to extract current queue and cursor from context and call a crawl function with setting initial queue and cursor. It did work, although I've managed to implement it only for bfs and it didn't show and performance superiority over async version. In my specific case async version solves also another minor problem, so I'll stick with it.

**Comment by ngryman** [comment]
Hey @mcalus3,

Sorry for the lack of answer, I got a little swamped by work lately...

My initial proposition was slightly naive indeed and yours could work actually. I think you would need to pass the whole "cursor" instead of the solely the stack/queue. But I suppose that such a change would also involve to patch the library's internals to make it work properly with all traversing strategies.

That's probably too much complexity given the fact that the `async`/`await` version is probably more valuable for the library. I would be curious to know how it affects the benchmarks though 🤔. If you still want to, I would accept a PR for that (given the condition that the benchmarks don't drop too much).
